"""se crea campo email y password

Revision ID: 1600dc79fc64
Revises: 746caca14a63
Create Date: 2022-10-08 08:42:01.526162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1600dc79fc64'
down_revision = '746caca14a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=True), schema='test_schema')
    op.add_column('users', sa.Column('password', sa.String(length=120), nullable=True), schema='test_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password', schema='test_schema')
    op.drop_column('users', 'email', schema='test_schema')
    # ### end Alembic commands ###
