"""se impide que el ombre y el apellido seal null

Revision ID: 746caca14a63
Revises: 25ffcca56de3
Create Date: 2022-09-25 12:05:28.891242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746caca14a63'
down_revision = '25ffcca56de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='test_schema')
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='test_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='test_schema')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='test_schema')
    # ### end Alembic commands ###
