"""se agrega last_name a Users

Revision ID: 25ffcca56de3
Revises: 95ef976f7230
Create Date: 2022-08-29 11:14:03.053000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ffcca56de3'
down_revision = '95ef976f7230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True), schema='test_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name', schema='test_schema')
    # ### end Alembic commands ###
