"""se corrige que el campo no puede ser null (email ni password)

Revision ID: 309c9535a0bf
Revises: 1600dc79fc64
Create Date: 2022-10-08 08:44:08.323899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309c9535a0bf'
down_revision = '1600dc79fc64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False,
               schema='test_schema')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=120),
               nullable=False,
               schema='test_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=120),
               nullable=True,
               schema='test_schema')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True,
               schema='test_schema')
    # ### end Alembic commands ###
