"""test

Revision ID: 4aaddfc48d29
Revises: 8e36ccfed795
Create Date: 2022-10-21 21:17:29.677308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aaddfc48d29'
down_revision = '8e36ccfed795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('test', sa.Boolean(), nullable=True), schema='test_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'test', schema='test_schema')
    # ### end Alembic commands ###
