"""se elimina campo last_name de users

Revision ID: 95ef976f7230
Revises: 68ec6913b753
Create Date: 2022-08-28 20:36:10.064963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ef976f7230'
down_revision = '68ec6913b753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name', schema='test_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True), schema='test_schema')
    # ### end Alembic commands ###
