"""test2

Revision ID: b815f6bf3f08
Revises: 4aaddfc48d29
Create Date: 2022-10-21 21:19:12.181018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b815f6bf3f08'
down_revision = '4aaddfc48d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'test', schema='test_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('test', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='test_schema')
    # ### end Alembic commands ###
