"""relacion entre usuarios y grupos

Revision ID: c50d07c0327f
Revises: a67f5a1ebc6a
Create Date: 2022-12-03 22:43:24.933865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50d07c0327f'
down_revision = 'a67f5a1ebc6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['authentication.groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['authentication.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id'),
    schema='authentication'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_groups', schema='authentication')
    # ### end Alembic commands ###
